package Diners;


/**
* Diners/IDinerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Diners.idl
* Wednesday, March 30, 2016 12:21:51 AM EDT
*/

public interface IDinerOperations 
{

  // put method specifications here
  void requestFromRight ();
  void requestFromLeft ();
  void forkFromRight ();
  void forkFromLeft ();
} // interface IDinerOperations
