package Diners;


/**
* Diners/IDinerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Diners.idl
* Wednesday, March 30, 2016 12:21:51 AM EDT
*/

abstract public class IDinerHelper
{
  private static String  _id = "IDL:Diners/IDiner:1.0";

  public static void insert (org.omg.CORBA.Any a, Diners.IDiner that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Diners.IDiner extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Diners.IDinerHelper.id (), "IDiner");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Diners.IDiner read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IDinerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Diners.IDiner value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Diners.IDiner narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Diners.IDiner)
      return (Diners.IDiner)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Diners._IDinerStub stub = new Diners._IDinerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Diners.IDiner unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Diners.IDiner)
      return (Diners.IDiner)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Diners._IDinerStub stub = new Diners._IDinerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
