package Diners;

/**
* Diners/IDinerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Diners.idl
* Wednesday, March 30, 2016 12:21:50 AM EDT
*/

public final class IDinerHolder implements org.omg.CORBA.portable.Streamable
{
  public Diners.IDiner value = null;

  public IDinerHolder ()
  {
  }

  public IDinerHolder (Diners.IDiner initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Diners.IDinerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Diners.IDinerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Diners.IDinerHelper.type ();
  }

}
